version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/project/docker-android

jobs:
  build:
    <<: *docker_defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and publish android Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t bellstrand/docker-android:$TAG .
    
            docker run bellstrand/docker-android:$TAG
            docker ps -a

            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push bellstrand/docker-android:$TAG
            

workflows:
  version: 2
  build-publish:
    jobs:
      - build
